"""Added submission history and linked submissions.

Revision ID: 03dd583914d0
Revises: 45b5cf6cc787
Create Date: 2024-04-06 03:19:37.915985

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '03dd583914d0'
down_revision = '45b5cf6cc787'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission_submitters',
    sa.Column('submission_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('submitter_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.ForeignKeyConstraint(['submitter_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('submission_id', 'submitter_id')
    )
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submission_number', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('submitted_at', postgresql.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False))
        batch_op.alter_column('score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=5, scale=3),
               existing_nullable=True)
        batch_op.drop_column('executed_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('executed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.alter_column('score',
               existing_type=sa.Numeric(precision=5, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.drop_column('active')
        batch_op.drop_column('submitted_at')
        batch_op.drop_column('submission_number')

    op.drop_table('submission_submitters')
    # ### end Alembic commands ###
