"""Added input logging to database for autograder uploads.

Revision ID: 45b5cf6cc787
Revises: 
Create Date: 2024-04-03 23:10:45.122193

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine import reflection

# revision identifiers, used by Alembic.
revision = '45b5cf6cc787'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = reflection.Inspector.from_engine(bind)
    
    if 'input_data' not in [col['name'] for col in inspector.get_columns('test_cases')]:
        # Add the 'input_data' column only if it doesn't exist
        with op.batch_alter_table('test_cases', schema=None) as batch_op:
            batch_op.add_column(sa.Column('input_data', sa.Text(), nullable=True))
        
        op.execute("UPDATE test_cases SET input_data = '' WHERE input_data IS NULL")
    
    with op.batch_alter_table('test_cases', schema=None) as batch_op:
        batch_op.alter_column('input_data', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_cases', schema=None) as batch_op:
        batch_op.drop_column('input_data')
    # ### end Alembic commands ###
    